"""新增库存流水出入库单盘点差异表

Revision ID: 0e9d94a70a7f
Revises: 3d4b5f27d751
Create Date: 2026-09-07 19:39:42.195750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9d94a70a7f'
down_revision: Union[str, Sequence[str], None] = '3d4b5f27d751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('ref_no', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movement_created_at'), 'inventory_movement', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movement_product_id'), 'inventory_movement', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_zone_id'), 'inventory_movement', ['zone_id'], unique=False)
    op.create_table('stock_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_orders_created_at'), 'stock_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_orders_order_no'), 'stock_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_stock_orders_product_id'), 'stock_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_orders_zone_id'), 'stock_orders', ['zone_id'], unique=False)
    op.create_table('stocktaking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktaking_order_no'), 'stocktaking', ['order_no'], unique=True)
    op.create_index(op.f('ix_stocktaking_zone_id'), 'stocktaking', ['zone_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktaking_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('book_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stocktaking_id'], ['stocktaking.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_stocktaking_id'), 'discrepancies', ['stocktaking_id'], unique=False)
    op.create_index(op.f('ix_discrepancies_zone_id'), 'discrepancies', ['zone_id'], unique=False)
    op.create_table('stocktaking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktaking_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('book_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('diff', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stocktaking_id'], ['stocktaking.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stocktaking_id', 'product_id', 'zone_id', name='uq_stocktaking_item')
    )
    op.create_index(op.f('ix_stocktaking_item_stocktaking_id'), 'stocktaking_item', ['stocktaking_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_unique_constraint('uq_inventory_product_zone', 'inventory', ['product_id', 'zone_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inventory_product_zone', 'inventory', type_='unique')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_stocktaking_item_stocktaking_id'), table_name='stocktaking_item')
    op.drop_table('stocktaking_item')
    op.drop_index(op.f('ix_discrepancies_zone_id'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_stocktaking_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_stocktaking_zone_id'), table_name='stocktaking')
    op.drop_index(op.f('ix_stocktaking_order_no'), table_name='stocktaking')
    op.drop_table('stocktaking')
    op.drop_index(op.f('ix_stock_orders_zone_id'), table_name='stock_orders')
    op.drop_index(op.f('ix_stock_orders_product_id'), table_name='stock_orders')
    op.drop_index(op.f('ix_stock_orders_order_no'), table_name='stock_orders')
    op.drop_index(op.f('ix_stock_orders_created_at'), table_name='stock_orders')
    op.drop_table('stock_orders')
    op.drop_index(op.f('ix_inventory_movement_zone_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_product_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_created_at'), table_name='inventory_movement')
    op.drop_table('inventory_movement')
    # ### end Alembic commands ###
