"""移除products冗余quantity字段

Revision ID: 3f7d3133d256
Revises: 0e9d94a70a7f
Create Date: 2026-09-07 19:53:38.879775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f7d3133d256'
down_revision: Union[str, Sequence[str], None] = '0e9d94a70a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
